// GENERATED by scripts/ratios.mjs. Do not edit; run the script.
//
// Width over height of each drawing's trimmed viewBox. Plates are sized by
// height and take their width from here, so no figure is ever stretched and no
// box carries padding the drawing does not fill.

export const RATIO: Record<string, number> = {
  "bass": 0.9595,
  "brazil": 0.821,
  "broken-racket": 0.8959,
  "broken-sticks": 0.9108,
  "camera": 1.0362,
  "deadlift": 0.4365,
  "drums": 1.0799,
  "falls": 1.322,
  "filmset": 0.8836,
  "finish": 0.44,
  "first-camera": 0.7269,
  "first-guitar": 0.7651,
  "first-racket": 1.2949,
  "graduation": 0.3398,
  "guitar": 0.942,
  "keys": 0.9163,
  "medal": 0.6808,
  "peter-pan": 0.4773,
  "running": 0.5381,
  "serve": 0.838,
  "tennis": 0.8274,
  "webcam-guitar": 1.1948,
  "working": 1.1391,
};

export type Drawing = keyof typeof RATIO;
