/**
 * Generates src/lib/ratios.ts from the drawings on disk.
 *
 * The field sizes every plate by HEIGHT, so that eighteen figures of one person
 * read as one person at one scale rather than as eighteen boxes. Width then has
 * to come from each drawing's own proportions, and those proportions live in the
 * viewBox, which scripts/tighten_viewbox.mjs already trimmed to the artwork.
 *
 * Generated rather than hand-typed because a retrace changes a viewBox, and a
 * hand-typed ratio would silently stretch a figure from then on. A test compares
 * the committed file against the files on disk, so drift fails the build.
 *
 *   node scripts/ratios.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = join(process.cwd(), "public", "drawings");
const OUT = join(process.cwd(), "src", "lib", "ratios.ts");

export function readRatios() {
  const out = {};

  for (const file of readdirSync(DIR).filter((f) => f.endsWith(".svg")).sort()) {
    const svg = readFileSync(join(DIR, file), "utf8");
    const box = svg.match(/viewBox="([^"]+)"/);
    if (!box) throw new Error(`${file} has no viewBox`);

    const [, , w, h] = box[1].trim().split(/\s+/).map(Number);
    if (!(w > 0 && h > 0)) throw new Error(`${file} has a degenerate viewBox`);

    const slug = file.replace(/^detail-/, "").replace(/\.svg$/, "");
    // Four places: at a 2000px plate, the next digit moves the box by 0.2px.
    out[slug] = Number((w / h).toFixed(4));
  }

  return out;
}

export function render(ratios) {
  const rows = Object.entries(ratios)
    .map(([slug, r]) => `  "${slug}": ${r},`)
    .join("\n");

  return `// GENERATED by scripts/ratios.mjs. Do not edit; run the script.
//
// Width over height of each drawing's trimmed viewBox. Plates are sized by
// height and take their width from here, so no figure is ever stretched and no
// box carries padding the drawing does not fill.

export const RATIO: Record<string, number> = {
${rows}
};

export type Drawing = keyof typeof RATIO;
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const ratios = readRatios();
  writeFileSync(OUT, render(ratios));
  console.log(`Wrote ${Object.keys(ratios).length} ratios to src/lib/ratios.ts`);
}
